version: 0.2

phases:
  install:
    commands:
      - echo Hello, CodeBuild Install!

  build:
    commands:
      - echo Hello, CodeBuild Build!
     
  post_build:
    commands:
      - echo Hello, CodeBuild PostBuild!
      - pwd
      - ls
      - aws --version
      - ./codebuild-ubuntu/install-java
      - java -version

#artifacts:
#  files:
#    - target/MyGroovy-1.0-SNAPSHOT.jar

