version: 0.2

phases:
  install:
    commands:
      - echo Hello, CodeBuild Install!
      - ./codebuild-ubuntu/install-grails
      - pwd

  build:
    commands:
      - echo Hello, CodeBuild Build!
      - pwd
      - /usr/local/share/grails-2.4.0/bin/grails war
     
  post_build:
    commands:
      - echo Hello, CodeBuild PostBuild!


artifacts:
  files:
    - target/microcero-0.1.war

