version: 0.2

phases:
  install:
    commands:
      - cat /proc/version
      - pwd
      - ls
      - sh install-maven
      - echo muy corta para odiar el lunes
#      - sh install-grails
      - sudo yum install java-1.7.0-openjdk-devel -y
      - export JAVA_HOME=/usr/lib/jvm/java
      - aws s3 cp s3://redf4rth-root/gocontainer/dotsdkman-grails.zip .
      - ls
      - echo dar gracias
#      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
#      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
#  pre_build:
#    commands:
#      - docker build -t helloworld .
#  build:
#    commands:
#      - docker images
#      - docker run helloworld echo "Hello, World!" 
