version: 0.2

phases:
  install:
    commands:
      - echo Hello, CodeBuild Install!
      - pwd
      - ls
#      - ./codebuild-ubuntu/install-grails
# Use sh instead of dot when running inside CodeBuild Ubuntu:
      - sh install-grails-for-codepipeline

  build:
    commands:
      - echo Hello, CodeBuild Build!
      - pwd
      - ls
#      - /usr/local/share/grails-2.4.0/bin/grails war ./craig.war > mito
#      - ls
       - mvn grails:war
    
  post_build:
    commands:
      - echo Hello, CodeBuild PostBuild!
      - ls


artifacts:
  files:
    - target/microcero-0.1.war

