AWSTemplateFormatVersion: "2010-09-09"
Parameters:
#  githubpassword:
#    Type: String
  ObjectKey:
    Type: String
  BucketName:
    Type: String
Resources:
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: craig-go-component
          Value: craig-go
      ImageId: "ami-7172b611"
      InstanceType: "t2.micro"
      KeyName: oregonkeypair
      SecurityGroupIds:
        - sg-2b0a9754 #a temporary security group
      IamInstanceProfile: RoleForTestingRoles
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://craigwongva/microcero\n"
              - "cd microcero\n"
              - "./install-tomcat\n"
              - "sleep 60"
              - "aws s3 cp "
              - Ref: BucketName
              - "/"
              - Ref: ObjectKey
              - " ./mywar.zip\n"
              - "unzip mywar.zip\n"
              - "cp Poder-0.1.war /usr/share/tomcat7/webapps/Poder.war\n"
