AWSTemplateFormatVersion: "2010-09-09"
Parameters:
#  githubpassword:
#    Type: String
  ObjectKey:
    Type: String
  BucketName:
    Type: String
Resources:
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: craig-go-component
          Value: craig-go
      ImageId: "ami-7172b611"
      InstanceType: "t2.micro"
      KeyName: oregonkeypair
      SecurityGroupIds:
        - sg-2b0a9754 #a temporary security group
      IamInstanceProfile: RoleForTestingRoles
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"
#              - "yum install git -y\n"
#              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone -b three https://craigwongva:"
              - "echo no odia3 " 
#              - Ref: githubpassword
              - " pregunta "
              - Ref: BucketName
              - " respuesta "
              - Ref: ObjectKey
              - " > /tmp/odia \n"
#              - "@github.com/craigwongva/saynext.git > /tmp/u10 2>&1 '\n"
#              - "sudo -u ec2-user bash -c '/home/ec2-user/saynext/userdata > /tmp/u20 2>&1'\n"            